// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipe.Infrastructure.Persistence;

#nullable disable

namespace Recipe.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605181916_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recipe.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("DietaryTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTimeMinutes = 30,
                            DietaryTag = "gluten,meat",
                            Ingredients = "Spaghetti, Tomato Sauce, Beef",
                            Steps = "Boil pasta, cook sauce, mix.",
                            Title = "Spaghetti Bolognese"
                        },
                        new
                        {
                            Id = 2,
                            CookingTimeMinutes = 20,
                            DietaryTag = "vegan,gluten-free",
                            Ingredients = "Tofu, Broccoli, Soy Sauce",
                            Steps = "Fry tofu, add veg, stir-fry.",
                            Title = "Vegan Tofu Stir Fry"
                        },
                        new
                        {
                            Id = 3,
                            CookingTimeMinutes = 10,
                            DietaryTag = "vegetarian",
                            Ingredients = "Bread, Avocado, Salt, Pepper",
                            Steps = "Toast bread, spread avocado.",
                            Title = "Avocado Toast"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
